
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author annoyverklone
 */
public class radiobuttontest extends javax.swing.JFrame {

    /**
     * Creates new form radiobuttontest
     */
    public radiobuttontest() {
        initComponents();
        setTitle("Data Karyawan Beta 0.1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PEND = new javax.swing.ButtonGroup();
        KELAMIN = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        NAMAFIELD = new javax.swing.JTextField();
        JENISKEL = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        sd = new javax.swing.JRadioButton();
        smp = new javax.swing.JRadioButton();
        sma = new javax.swing.JRadioButton();
        s1 = new javax.swing.JRadioButton();
        al = new javax.swing.JLabel();
        alamatfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        PREVIEW = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        title.setText(" DATA KARYAWAN");

        NAMA.setText("NAMA");

        NAMAFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAFIELDActionPerformed(evt);
            }
        });

        JENISKEL.setText("JENIS KELAMIN");

        KELAMIN.add(laki);
        laki.setText("LAKI - LAKI");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });

        KELAMIN.add(perempuan);
        perempuan.setText("PEREMPUAN");
        perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanActionPerformed(evt);
            }
        });

        jLabel1.setText("PENDIDIKAN");

        PEND.add(sd);
        sd.setText("SD");

        PEND.add(smp);
        smp.setText("SMP");

        PEND.add(sma);
        sma.setText("SMA");
        sma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smaActionPerformed(evt);
            }
        });

        PEND.add(s1);
        s1.setText("S1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        al.setText("ALAMAT");

        alamatfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatfieldActionPerformed(evt);
            }
        });

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        PREVIEW.setText("PREVIEW");
        PREVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREVIEWActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAMA)
                            .addComponent(JENISKEL)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(al)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sma, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laki)
                        .addGap(18, 18, 18)
                        .addComponent(perempuan))
                    .addComponent(NAMAFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatfield, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PREVIEW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CLEAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA)
                    .addComponent(NAMAFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JENISKEL)
                    .addComponent(laki)
                    .addComponent(perempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sd)
                    .addComponent(smp)
                    .addComponent(sma)
                    .addComponent(s1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(al)
                    .addComponent(alamatfield, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PREVIEW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CLEAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAVE))
                    .addComponent(jScrollPane1))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMAFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAFIELDActionPerformed
        String text = NAMAFIELD.getText();
        textarea.setText(text);
    }//GEN-LAST:event_NAMAFIELDActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanActionPerformed

    private void smaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smaActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void alamatfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatfieldActionPerformed
        String text = alamatfield.getText();
        textarea.setText(text);

    }//GEN-LAST:event_alamatfieldActionPerformed

    private void PREVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREVIEWActionPerformed
        textarea.append("NAMA\t: " + NAMAFIELD.getText() + "\n"); //show NAMA field on textarea
        if(laki.isSelected()){
            textarea.append("Jenis Kelamin\t: "+laki.getText()+"\n"); //show on textarea
        }else if(perempuan.isSelected()){
            textarea.append("Jenis Kelamin\t: "+perempuan.getText()+"\n"); //show on textarea
        }else if(sd.isSelected()){
            textarea.append("Pendidikan\t: "+sd.getText()+"\n"); //tampil pilihan butto di textarea
        }else if (smp.isSelected()){
            textarea.append("Pendidikan\t: "+smp.getText()+"\n"); //tampil pilihan butto di textarea
        }else if (sma.isSelected()){
            textarea.append("Pendidikan\t: "+sma.getText()+"\n"); //tampil pilihan butto di textarea
        }else if (s1.isSelected()){
            textarea.append("Pendidikan\t: "+s1.getText()+"\n"); //tampil pilihan butto di textarea
        }else{
            JOptionPane.showMessageDialog(null,"No button selected,Please Insert Data");
            //pesan error jika tidak ada data yang dimasukkan
        }
        textarea.append("Alamat\t: " + alamatfield.getText()+"\n"); //tampil alamat di textarea
    }//GEN-LAST:event_PREVIEWActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        String data  = textarea.getText().trim();
        if (data.equals("")) {
            JOptionPane.showMessageDialog(null, "Doesnt have data on textarea");
        }else{
            JOptionPane.showMessageDialog(null, "Thank You for update the data"); 
        }
        
        try {
            BufferedWriter take = new BufferedWriter(new FileWriter("data1.txt"));
            BufferedReader linereader = new BufferedReader(new FileReader("data1.txt"));
            take.write(System.getProperty("line.separator"));
            textarea.write(take);
            take.close();
            textarea.setText("");
            textarea.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        NAMAFIELD.setText("");
        PEND.clearSelection();
        alamatfield.setText("");
        KELAMIN.clearSelection();
        NAMAFIELD.requestFocus();
        textarea.setText("");
        
    }//GEN-LAST:event_CLEARActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radiobuttontest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radiobuttontest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radiobuttontest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radiobuttontest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radiobuttontest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JLabel JENISKEL;
    private javax.swing.ButtonGroup KELAMIN;
    private javax.swing.JLabel NAMA;
    private javax.swing.JTextField NAMAFIELD;
    private javax.swing.ButtonGroup PEND;
    private javax.swing.JButton PREVIEW;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel al;
    private javax.swing.JTextField alamatfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton sd;
    private javax.swing.JRadioButton sma;
    private javax.swing.JRadioButton smp;
    private javax.swing.JTextArea textarea;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
